import { Category, Project } from "@/types/project";

export const categories: Category[] = [
  {
    id: "1",
    name: "Frontend",
    slug: "frontend",
    color: "bg-emerald-500/15 text-emerald-700 dark:text-emerald-400",
    projectCount: 12,
    createdAt: "2025-01-15",
  },
  {
    id: "2",
    name: "Backend",
    slug: "backend",
    color: "bg-blue-500/15 text-blue-700 dark:text-blue-400",
    projectCount: 8,
    createdAt: "2025-01-15",
  },
  {
    id: "3",
    name: "Full Stack",
    slug: "full-stack",
    color: "bg-amber-500/15 text-amber-700 dark:text-amber-400",
    projectCount: 15,
    createdAt: "2025-01-20",
  },
  {
    id: "4",
    name: "Mobile",
    slug: "mobile",
    color: "bg-rose-500/15 text-rose-700 dark:text-rose-400",
    projectCount: 6,
    createdAt: "2025-02-01",
  },
  {
    id: "5",
    name: "DevOps",
    slug: "devops",
    color: "bg-cyan-500/15 text-cyan-700 dark:text-cyan-400",
    projectCount: 4,
    createdAt: "2025-02-10",
  },
  {
    id: "6",
    name: "AI / ML",
    slug: "ai-ml",
    color: "bg-fuchsia-500/15 text-fuchsia-700 dark:text-fuchsia-400",
    projectCount: 10,
    createdAt: "2025-02-15",
  },
  {
    id: "7",
    name: "Open Source",
    slug: "open-source",
    color: "bg-teal-500/15 text-teal-700 dark:text-teal-400",
    projectCount: 20,
    createdAt: "2025-03-01",
  },
  {
    id: "8",
    name: "CLI Tools",
    slug: "cli-tools",
    color: "bg-orange-500/15 text-orange-700 dark:text-orange-400",
    projectCount: 3,
    createdAt: "2025-03-10",
  },
];

export const projects: Project[] = [
  {
    id: "1",
    title: "Next.js SaaS Boilerplate",
    description:
      "A production-ready SaaS starter kit built with Next.js 15, Tailwind CSS, and Supabase. Includes authentication, billing, team management, and a beautiful dashboard.",
    githubUrl: "https://github.com/acme/saas-boilerplate",
    websiteUrl: "https://saas-starter.dev",
    categories: [categories[0], categories[2]],
    status: "approved",
    authorName: "Sarah Chen",
    authorEmail: "sarah@example.com",
    authorAvatar: "",
    createdAt: "2025-12-01",
    updatedAt: "2025-12-05",
  },
  {
    id: "2",
    title: "AI Image Generator API",
    description:
      "RESTful API for generating images using stable diffusion models. Supports multiple output formats, batch processing, and custom model fine-tuning with a simple SDK.",
    githubUrl: "https://github.com/acme/ai-image-gen",
    websiteUrl: "https://ai-images.api.dev",
    categories: [categories[1], categories[5]],
    status: "approved",
    authorName: "Marcus Johnson",
    authorEmail: "marcus@example.com",
    authorAvatar: "",
    createdAt: "2025-11-28",
    updatedAt: "2025-12-02",
  },
  {
    id: "3",
    title: "React Native Fitness Tracker",
    description:
      "Cross-platform mobile app for tracking workouts, nutrition, and health metrics. Features beautiful charts, social sharing, and integration with Apple Health and Google Fit.",
    githubUrl: "https://github.com/acme/fitness-tracker",
    websiteUrl: "https://fittrack.app",
    categories: [categories[3], categories[0]],
    status: "approved",
    authorName: "Emily Davis",
    authorEmail: "emily@example.com",
    authorAvatar: "",
    createdAt: "2025-11-20",
    updatedAt: "2025-11-25",
  },
  {
    id: "4",
    title: "Kubernetes Deployment CLI",
    description:
      "Streamlined CLI tool for managing Kubernetes deployments across multiple clusters. Simplifies rollbacks, canary deployments, and monitoring with intuitive commands.",
    githubUrl: "https://github.com/acme/k8s-deploy-cli",
    websiteUrl: "",
    categories: [categories[4], categories[7]],
    status: "approved",
    authorName: "Alex Rivera",
    authorEmail: "alex@example.com",
    authorAvatar: "",
    createdAt: "2025-11-15",
    updatedAt: "2025-11-18",
  },
  {
    id: "5",
    title: "GraphQL Code Generator",
    description:
      "Automatically generates TypeScript types and React hooks from your GraphQL schema. Supports custom templates, incremental generation, and watch mode for development.",
    githubUrl: "https://github.com/acme/graphql-codegen",
    websiteUrl: "https://gql-gen.tools",
    categories: [categories[0], categories[1], categories[6]],
    status: "approved",
    authorName: "Priya Patel",
    authorEmail: "priya@example.com",
    authorAvatar: "",
    createdAt: "2025-11-10",
    updatedAt: "2025-11-12",
  },
  {
    id: "6",
    title: "Real-time Collaboration Engine",
    description:
      "WebSocket-based engine for building real-time collaborative applications. Supports conflict resolution, presence awareness, and offline sync with a simple API.",
    githubUrl: "https://github.com/acme/collab-engine",
    websiteUrl: "https://collab-engine.io",
    categories: [categories[1], categories[2], categories[6]],
    status: "pending",
    authorName: "Jordan Lee",
    authorEmail: "jordan@example.com",
    authorAvatar: "",
    createdAt: "2025-12-06",
    updatedAt: "2025-12-06",
  },
  {
    id: "7",
    title: "ML Model Serving Platform",
    description:
      "Deploy and serve machine learning models at scale. Includes auto-scaling, A/B testing, monitoring dashboards, and support for TensorFlow, PyTorch, and ONNX models.",
    githubUrl: "https://github.com/acme/ml-serve",
    websiteUrl: "https://mlserve.cloud",
    categories: [categories[5], categories[4]],
    status: "pending",
    authorName: "Taylor Kim",
    authorEmail: "taylor@example.com",
    authorAvatar: "",
    createdAt: "2025-12-07",
    updatedAt: "2025-12-07",
  },
  {
    id: "8",
    title: "Design System Builder",
    description:
      "Visual tool for creating and maintaining design systems. Generates component libraries, documentation, and Figma-to-code exports with a drag-and-drop interface.",
    githubUrl: "https://github.com/acme/design-system-builder",
    websiteUrl: "https://ds-builder.app",
    categories: [categories[0], categories[6]],
    status: "pending",
    authorName: "Sam Williams",
    authorEmail: "sam@example.com",
    authorAvatar: "",
    createdAt: "2025-12-08",
    updatedAt: "2025-12-08",
  },
  {
    id: "9",
    title: "Serverless Database Proxy",
    description:
      "Lightweight proxy layer for serverless functions to efficiently connect to traditional databases. Features connection pooling, caching, and query optimization.",
    githubUrl: "https://github.com/acme/serverless-db-proxy",
    websiteUrl: "",
    categories: [categories[1], categories[4]],
    status: "rejected",
    authorName: "Chris Morgan",
    authorEmail: "chris@example.com",
    authorAvatar: "",
    createdAt: "2025-11-05",
    updatedAt: "2025-11-08",
  },
  {
    id: "10",
    title: "E-commerce Component Library",
    description:
      "Pre-built React components for building e-commerce storefronts. Includes product cards, shopping carts, checkout flows, and payment integration components.",
    githubUrl: "https://github.com/acme/ecommerce-ui",
    websiteUrl: "https://ecommerce-ui.dev",
    categories: [categories[0], categories[6]],
    status: "approved",
    authorName: "Maria Garcia",
    authorEmail: "maria@example.com",
    authorAvatar: "",
    createdAt: "2025-10-20",
    updatedAt: "2025-10-28",
  },
  {
    id: "11",
    title: "Automated Testing Framework",
    description:
      "End-to-end testing framework that uses AI to generate test cases from user stories. Supports visual regression testing, cross-browser testing, and CI/CD integration.",
    githubUrl: "https://github.com/acme/auto-test",
    websiteUrl: "https://autotest.dev",
    categories: [categories[4], categories[5], categories[6]],
    status: "approved",
    authorName: "David Park",
    authorEmail: "david@example.com",
    authorAvatar: "",
    createdAt: "2025-10-15",
    updatedAt: "2025-10-22",
  },
  {
    id: "12",
    title: "Markdown Note-Taking App",
    description:
      "Beautiful Markdown editor with real-time preview, file organization, tagging, and cloud sync. Built with React Native for iOS and Android with offline support.",
    githubUrl: "https://github.com/acme/md-notes",
    websiteUrl: "https://mdnotes.app",
    categories: [categories[3], categories[0]],
    status: "approved",
    authorName: "Lisa Wang",
    authorEmail: "lisa@example.com",
    authorAvatar: "",
    createdAt: "2025-10-08",
    updatedAt: "2025-10-12",
  },
];

// current user's projects
export const myProjects = projects.filter(
  (p) =>
    p.authorEmail === "sarah@example.com" ||
    p.authorEmail === "jordan@example.com" ||
    p.authorEmail === "chris@example.com"
);

// pending projects for admin
export const pendingProjects = projects.filter((p) => p.status === "pending");
